// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGb5H5FGG69vEJ039KZihIvpf_uqT4xM',
    appId: '1:997979588709:android:c12cb00419e89664521e8c',
    messagingSenderId: '997979588709',
    projectId: 'fav-places-6b93a',
    storageBucket: 'fav-places-6b93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVE38DUxw7bIK4WgsYBuTVo1AY3pjlcu0',
    appId: '1:997979588709:ios:bd209f64cdae34dd521e8c',
    messagingSenderId: '997979588709',
    projectId: 'fav-places-6b93a',
    storageBucket: 'fav-places-6b93a.appspot.com',
    androidClientId: '997979588709-aev6ju9rjl1m1kok9udivgq6anrif1rm.apps.googleusercontent.com',
    iosClientId: '997979588709-alpiepnggcrss9vsulmtc5ld8rrjubrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.favPlaces',
  );
}
